# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk
# Run with:
# docker-compose up

version: '3'
services:
  elk:
    build: .
    image: kdefoe/elk-capstone:1.2
    ports:
      - "5601:5601"  # Kibana
      - "9200:9200"  # Elasticsearch
      - "5044:5044"  # Logstash Beats input
      - "8000:8000"  # upload server
    volumes:
      - /usr/share/logstash/data/uploads:/usr/share/logstash/data/uploads  # Volume for uploads
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data  # Persistent volume for Elasticsearch
      - /usr/share/kibana/data:/usr/share/kibana/data  # Persistent volume for Kibana dashboards
      - /usr/share/logstash/data/:/usr/share/logstash/data/ #logstash volume

volumes:
  logstash-uploads:
    driver: local
  elasticsearch-data:
    driver: local

